# Rename this file to languages.toml to enable multilingual support
[zh-cn]
languageName = "简体中文"
title = "信息小杨的博客"
weight = 1
[en]
languageName = "English"
languagedirection = "ltr"
title = "Yz blog"
weight = 2

